### ISSUE TITLE
Controlling blinds

### ISSUE THREAD

**Issue by Shogun1978** [originallyus/node-red-contrib-alexa-local#5]
First of all: great work and big thank you! I use to control my Loxone smart home 👍 
Is it somehow possible to say "Alexa, close livingroom blind"? Currently I use "Alexa, set livingroom blind to x percent." Works great, but sounds completely strange.

By the way: it works with the german Alexa!

**Comment by torinnguyen** [comment]
Unfortunately no. In order to keep this node so simple to use. It was designed to emulate a Philips Hue bridge & device within local network. Amazon Echo is hardcoded to support only on/off/dimming command via this route. Any other type of support has to go through the Alexa Skills route (cloud-based). There is another node does just that [node-red-contrib-alexa-home-skill](https://github.com/hardillb/node-red-contrib-alexa-home-skill)

**Comment by Shogun1978** [comment]
Ok, thank you for the fast response. I know this node and already tried it. Basically, I can control blinds with the node-red-contrib-alexa-home-skill like I do with your contrib. But I don't need any server in the backend. I already tried my own Amazon skill, but don't like using a keyword for it. So for now: "Alexa, set blinds to x percent" :-) I would be happy, if you extend the skill (create another) for blinds, getting/setting temperatures etc.

**Comment by burleanu** [comment]
hello @Shogun1978  I think I found a solution  for your request.
Inside the Alexa app on the phone you  have a page called "routines" and in there you can say what you want to Alexa. So you can make a routine for opening the blinds and another to close them.
Or anything you like to say  and what Alexa will have to do to that words.
